### ISSUE TITLE
When I bind the value in my model, it auto-expands the autocomplete

### ISSUE THREAD

**Issue by nathanchase** [aurelia-plugins/aurelia-plugins-google-places-autocomplete#2]
Is there a way to immediately blur the autocomplete `<aup-google-places-autocomplete></aup-google-places-autocomplete>` immediately after binding its value?

I saw there was a `blur()` method, but I'm unclear as to how to access it.

So I'm setting the value like so:
```
this.locationName = "Orlando, Florida";
this.value = this.locationName;
```
and when my view loads, it successfully drops Orlando, Florida into the input, but then the autocomplete automatically shows, sends it through to the Google Places API, and tries to suggest...

So, can I programatically do something like `this.autocomplete.blur()` in my viewmodel code?

**Comment by bartlenaerts** [comment]
Hi Nathan,
the reason why the suggestion kicks in immediately after you set the 'value' property is because we use the 'valueChanged' function of Aurelia to react on the input.
What are you trying to achieve? Putting already an value in the textbox through your viewmodel without any action to the Google Places API? When does the suggestions need to be shown? After you press 'enter'?
Maybe I can make an option for this; do auto-magic or wait for manual action...??
Greetz, Bart

**Comment by nathanchase** [comment]
Hey, Bart!

Yeah, we're using the plugin as a means of capturing a user's location, so when they load the view, it pulls their stored location from our database and populates the input with that data (`this.user.location`).

So, the placeholder works great when there's no location yet, but after a user has already entered the data and saved it, and they come back to this "edit profile" view, their location name string is bound to the textbox, and it's automatically creating the suggestion dropdown.

We need it to not do that unless a user:

A) clicks/taps in the textbox
B) or otherwise navigates (maybe using tab on keyboard) to that input and starts typing/editing the field

**Comment by bartlenaerts** [comment]
Fixed!

**Comment by nathanchase** [comment]
Awesome! Works perfectly now. Many thanks & much appreciated!
